### ISSUE TITLE
setup requires upgraded pip

### ISSUE THREAD

**Issue by jbpratt** [piqe-test-libraries/piqe-ocp-lib#48]
RHEL CSB comes with python3.6 as default with pip 9.x.x being the version available. To follow the install instructions with the poetry config, it is required that users upgrade the pip version (which is spit out as a warning. Pip just fails out complaining about a missing `setup.py` file otherwise.

`python -m pip install --upgrade pip` 

It may be worth documenting the requirement, this was something @kasturinarra was running into but it wasn't immediately clear to us why. Otherwise, feel free to close this :cat:

**Comment by Dannyb48** [comment]
Closing this as this should be fixed with PR #61
